// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix
{
    [AviatrixResourceType("aviatrix:index/aviatrixCloudwatchAgent:AviatrixCloudwatchAgent")]
    public partial class AviatrixCloudwatchAgent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// CloudWatch role ARN.
        /// </summary>
        [Output("cloudwatchRoleArn")]
        public Output<string> CloudwatchRoleArn { get; private set; } = null!;

        /// <summary>
        /// List of excluded gateways.
        /// </summary>
        [Output("excludedGateways")]
        public Output<ImmutableArray<string>> ExcludedGateways { get; private set; } = null!;

        /// <summary>
        /// Log group name.
        /// </summary>
        [Output("logGroupName")]
        public Output<string?> LogGroupName { get; private set; } = null!;

        /// <summary>
        /// Name of AWS region.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Enabled or not.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a AviatrixCloudwatchAgent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AviatrixCloudwatchAgent(string name, AviatrixCloudwatchAgentArgs args, CustomResourceOptions? options = null)
            : base("aviatrix:index/aviatrixCloudwatchAgent:AviatrixCloudwatchAgent", name, args ?? new AviatrixCloudwatchAgentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AviatrixCloudwatchAgent(string name, Input<string> id, AviatrixCloudwatchAgentState? state = null, CustomResourceOptions? options = null)
            : base("aviatrix:index/aviatrixCloudwatchAgent:AviatrixCloudwatchAgent", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/astipkovits",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AviatrixCloudwatchAgent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AviatrixCloudwatchAgent Get(string name, Input<string> id, AviatrixCloudwatchAgentState? state = null, CustomResourceOptions? options = null)
        {
            return new AviatrixCloudwatchAgent(name, id, state, options);
        }
    }

    public sealed class AviatrixCloudwatchAgentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CloudWatch role ARN.
        /// </summary>
        [Input("cloudwatchRoleArn", required: true)]
        public Input<string> CloudwatchRoleArn { get; set; } = null!;

        [Input("excludedGateways")]
        private InputList<string>? _excludedGateways;

        /// <summary>
        /// List of excluded gateways.
        /// </summary>
        public InputList<string> ExcludedGateways
        {
            get => _excludedGateways ?? (_excludedGateways = new InputList<string>());
            set => _excludedGateways = value;
        }

        /// <summary>
        /// Log group name.
        /// </summary>
        [Input("logGroupName")]
        public Input<string>? LogGroupName { get; set; }

        /// <summary>
        /// Name of AWS region.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public AviatrixCloudwatchAgentArgs()
        {
        }
        public static new AviatrixCloudwatchAgentArgs Empty => new AviatrixCloudwatchAgentArgs();
    }

    public sealed class AviatrixCloudwatchAgentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CloudWatch role ARN.
        /// </summary>
        [Input("cloudwatchRoleArn")]
        public Input<string>? CloudwatchRoleArn { get; set; }

        [Input("excludedGateways")]
        private InputList<string>? _excludedGateways;

        /// <summary>
        /// List of excluded gateways.
        /// </summary>
        public InputList<string> ExcludedGateways
        {
            get => _excludedGateways ?? (_excludedGateways = new InputList<string>());
            set => _excludedGateways = value;
        }

        /// <summary>
        /// Log group name.
        /// </summary>
        [Input("logGroupName")]
        public Input<string>? LogGroupName { get; set; }

        /// <summary>
        /// Name of AWS region.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Enabled or not.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public AviatrixCloudwatchAgentState()
        {
        }
        public static new AviatrixCloudwatchAgentState Empty => new AviatrixCloudwatchAgentState();
    }
}
