// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix
{
    [AviatrixResourceType("aviatrix:index/aviatrixControllerBgpMaxAsLimitConfig:AviatrixControllerBgpMaxAsLimitConfig")]
    public partial class AviatrixControllerBgpMaxAsLimitConfig : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The maximum AS path limit allowed by transit gateways when handling BGP/Peering route propagation.
        /// </summary>
        [Output("maxAsLimit")]
        public Output<int> MaxAsLimit { get; private set; } = null!;


        /// <summary>
        /// Create a AviatrixControllerBgpMaxAsLimitConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AviatrixControllerBgpMaxAsLimitConfig(string name, AviatrixControllerBgpMaxAsLimitConfigArgs args, CustomResourceOptions? options = null)
            : base("aviatrix:index/aviatrixControllerBgpMaxAsLimitConfig:AviatrixControllerBgpMaxAsLimitConfig", name, args ?? new AviatrixControllerBgpMaxAsLimitConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AviatrixControllerBgpMaxAsLimitConfig(string name, Input<string> id, AviatrixControllerBgpMaxAsLimitConfigState? state = null, CustomResourceOptions? options = null)
            : base("aviatrix:index/aviatrixControllerBgpMaxAsLimitConfig:AviatrixControllerBgpMaxAsLimitConfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/astipkovits",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AviatrixControllerBgpMaxAsLimitConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AviatrixControllerBgpMaxAsLimitConfig Get(string name, Input<string> id, AviatrixControllerBgpMaxAsLimitConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new AviatrixControllerBgpMaxAsLimitConfig(name, id, state, options);
        }
    }

    public sealed class AviatrixControllerBgpMaxAsLimitConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The maximum AS path limit allowed by transit gateways when handling BGP/Peering route propagation.
        /// </summary>
        [Input("maxAsLimit", required: true)]
        public Input<int> MaxAsLimit { get; set; } = null!;

        public AviatrixControllerBgpMaxAsLimitConfigArgs()
        {
        }
        public static new AviatrixControllerBgpMaxAsLimitConfigArgs Empty => new AviatrixControllerBgpMaxAsLimitConfigArgs();
    }

    public sealed class AviatrixControllerBgpMaxAsLimitConfigState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The maximum AS path limit allowed by transit gateways when handling BGP/Peering route propagation.
        /// </summary>
        [Input("maxAsLimit")]
        public Input<int>? MaxAsLimit { get; set; }

        public AviatrixControllerBgpMaxAsLimitConfigState()
        {
        }
        public static new AviatrixControllerBgpMaxAsLimitConfigState Empty => new AviatrixControllerBgpMaxAsLimitConfigState();
    }
}
