// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix.Outputs
{

    [OutputType]
    public sealed class AviatrixTransitGatewayBgpLanInterface
    {
        public readonly string Subnet;
        public readonly string VpcId;

        [OutputConstructor]
        private AviatrixTransitGatewayBgpLanInterface(
            string subnet,

            string vpcId)
        {
            Subnet = subnet;
            VpcId = vpcId;
        }
    }
}
