// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix.Outputs
{

    [OutputType]
    public sealed class AviatrixAwsTgwSecurityDomainAttachedVpc
    {
        public readonly string? CustomizedRouteAdvertisement;
        public readonly string? CustomizedRoutes;
        public readonly bool? DisableLocalRoutePropagation;
        public readonly string? RouteTables;
        public readonly string? Subnets;
        public readonly string VpcAccountName;
        public readonly string VpcId;
        public readonly string VpcRegion;

        [OutputConstructor]
        private AviatrixAwsTgwSecurityDomainAttachedVpc(
            string? customizedRouteAdvertisement,

            string? customizedRoutes,

            bool? disableLocalRoutePropagation,

            string? routeTables,

            string? subnets,

            string vpcAccountName,

            string vpcId,

            string vpcRegion)
        {
            CustomizedRouteAdvertisement = customizedRouteAdvertisement;
            CustomizedRoutes = customizedRoutes;
            DisableLocalRoutePropagation = disableLocalRoutePropagation;
            RouteTables = routeTables;
            Subnets = subnets;
            VpcAccountName = vpcAccountName;
            VpcId = vpcId;
            VpcRegion = vpcRegion;
        }
    }
}
