// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix.Outputs
{

    [OutputType]
    public sealed class GetAviatrixFirewallInstanceImagesFirewallImageResult
    {
        public readonly string FirewallImage;
        public readonly ImmutableArray<string> FirewallImageVersions;
        public readonly ImmutableArray<string> FirewallSizes;

        [OutputConstructor]
        private GetAviatrixFirewallInstanceImagesFirewallImageResult(
            string firewallImage,

            ImmutableArray<string> firewallImageVersions,

            ImmutableArray<string> firewallSizes)
        {
            FirewallImage = firewallImage;
            FirewallImageVersions = firewallImageVersions;
            FirewallSizes = firewallSizes;
        }
    }
}
