// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aviatrix

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AviatrixAwsTgw struct {
	pulumi.CustomResourceState

	// This parameter represents the name of a Cloud-Account in Aviatrix controller.
	AccountName pulumi.StringOutput `pulumi:"accountName"`
	// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
	//
	// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
	AttachedAviatrixTransitGateways pulumi.StringArrayOutput `pulumi:"attachedAviatrixTransitGateways"`
	// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
	AwsSideAsNumber pulumi.StringOutput `pulumi:"awsSideAsNumber"`
	// TGW CIDRs.
	Cidrs pulumi.StringArrayOutput `pulumi:"cidrs"`
	// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
	CloudType pulumi.IntPtrOutput `pulumi:"cloudType"`
	// Enable Multicast.
	EnableMulticast pulumi.BoolPtrOutput `pulumi:"enableMulticast"`
	// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
	InspectionMode pulumi.StringPtrOutput `pulumi:"inspectionMode"`
	// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
	// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
	ManageSecurityDomain pulumi.BoolPtrOutput `pulumi:"manageSecurityDomain"`
	// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
	// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
	ManageTransitGatewayAttachment pulumi.BoolPtrOutput `pulumi:"manageTransitGatewayAttachment"`
	// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
	// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
	ManageVpcAttachment pulumi.BoolPtrOutput `pulumi:"manageVpcAttachment"`
	// Region of cloud provider.
	Region pulumi.StringOutput `pulumi:"region"`
	// Security Domains to create together with AWS TGW's creation.
	//
	// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
	SecurityDomains AviatrixAwsTgwSecurityDomainTypeArrayOutput `pulumi:"securityDomains"`
	// TGW ID.
	TgwId pulumi.StringOutput `pulumi:"tgwId"`
	// Name of the AWS TGW which is going to be created.
	TgwName pulumi.StringOutput `pulumi:"tgwName"`
}

// NewAviatrixAwsTgw registers a new resource with the given unique name, arguments, and options.
func NewAviatrixAwsTgw(ctx *pulumi.Context,
	name string, args *AviatrixAwsTgwArgs, opts ...pulumi.ResourceOption) (*AviatrixAwsTgw, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountName == nil {
		return nil, errors.New("invalid value for required argument 'AccountName'")
	}
	if args.AwsSideAsNumber == nil {
		return nil, errors.New("invalid value for required argument 'AwsSideAsNumber'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.TgwName == nil {
		return nil, errors.New("invalid value for required argument 'TgwName'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource AviatrixAwsTgw
	err := ctx.RegisterResource("aviatrix:index/aviatrixAwsTgw:AviatrixAwsTgw", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAviatrixAwsTgw gets an existing AviatrixAwsTgw resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAviatrixAwsTgw(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AviatrixAwsTgwState, opts ...pulumi.ResourceOption) (*AviatrixAwsTgw, error) {
	var resource AviatrixAwsTgw
	err := ctx.ReadResource("aviatrix:index/aviatrixAwsTgw:AviatrixAwsTgw", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AviatrixAwsTgw resources.
type aviatrixAwsTgwState struct {
	// This parameter represents the name of a Cloud-Account in Aviatrix controller.
	AccountName *string `pulumi:"accountName"`
	// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
	//
	// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
	AttachedAviatrixTransitGateways []string `pulumi:"attachedAviatrixTransitGateways"`
	// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
	AwsSideAsNumber *string `pulumi:"awsSideAsNumber"`
	// TGW CIDRs.
	Cidrs []string `pulumi:"cidrs"`
	// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
	CloudType *int `pulumi:"cloudType"`
	// Enable Multicast.
	EnableMulticast *bool `pulumi:"enableMulticast"`
	// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
	InspectionMode *string `pulumi:"inspectionMode"`
	// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
	// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
	ManageSecurityDomain *bool `pulumi:"manageSecurityDomain"`
	// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
	// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
	ManageTransitGatewayAttachment *bool `pulumi:"manageTransitGatewayAttachment"`
	// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
	// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
	ManageVpcAttachment *bool `pulumi:"manageVpcAttachment"`
	// Region of cloud provider.
	Region *string `pulumi:"region"`
	// Security Domains to create together with AWS TGW's creation.
	//
	// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
	SecurityDomains []AviatrixAwsTgwSecurityDomainType `pulumi:"securityDomains"`
	// TGW ID.
	TgwId *string `pulumi:"tgwId"`
	// Name of the AWS TGW which is going to be created.
	TgwName *string `pulumi:"tgwName"`
}

type AviatrixAwsTgwState struct {
	// This parameter represents the name of a Cloud-Account in Aviatrix controller.
	AccountName pulumi.StringPtrInput
	// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
	//
	// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
	AttachedAviatrixTransitGateways pulumi.StringArrayInput
	// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
	AwsSideAsNumber pulumi.StringPtrInput
	// TGW CIDRs.
	Cidrs pulumi.StringArrayInput
	// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
	CloudType pulumi.IntPtrInput
	// Enable Multicast.
	EnableMulticast pulumi.BoolPtrInput
	// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
	InspectionMode pulumi.StringPtrInput
	// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
	// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
	ManageSecurityDomain pulumi.BoolPtrInput
	// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
	// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
	ManageTransitGatewayAttachment pulumi.BoolPtrInput
	// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
	// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
	ManageVpcAttachment pulumi.BoolPtrInput
	// Region of cloud provider.
	Region pulumi.StringPtrInput
	// Security Domains to create together with AWS TGW's creation.
	//
	// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
	SecurityDomains AviatrixAwsTgwSecurityDomainTypeArrayInput
	// TGW ID.
	TgwId pulumi.StringPtrInput
	// Name of the AWS TGW which is going to be created.
	TgwName pulumi.StringPtrInput
}

func (AviatrixAwsTgwState) ElementType() reflect.Type {
	return reflect.TypeOf((*aviatrixAwsTgwState)(nil)).Elem()
}

type aviatrixAwsTgwArgs struct {
	// This parameter represents the name of a Cloud-Account in Aviatrix controller.
	AccountName string `pulumi:"accountName"`
	// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
	//
	// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
	AttachedAviatrixTransitGateways []string `pulumi:"attachedAviatrixTransitGateways"`
	// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
	AwsSideAsNumber string `pulumi:"awsSideAsNumber"`
	// TGW CIDRs.
	Cidrs []string `pulumi:"cidrs"`
	// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
	CloudType *int `pulumi:"cloudType"`
	// Enable Multicast.
	EnableMulticast *bool `pulumi:"enableMulticast"`
	// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
	InspectionMode *string `pulumi:"inspectionMode"`
	// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
	// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
	ManageSecurityDomain *bool `pulumi:"manageSecurityDomain"`
	// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
	// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
	ManageTransitGatewayAttachment *bool `pulumi:"manageTransitGatewayAttachment"`
	// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
	// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
	ManageVpcAttachment *bool `pulumi:"manageVpcAttachment"`
	// Region of cloud provider.
	Region string `pulumi:"region"`
	// Security Domains to create together with AWS TGW's creation.
	//
	// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
	SecurityDomains []AviatrixAwsTgwSecurityDomainType `pulumi:"securityDomains"`
	// Name of the AWS TGW which is going to be created.
	TgwName string `pulumi:"tgwName"`
}

// The set of arguments for constructing a AviatrixAwsTgw resource.
type AviatrixAwsTgwArgs struct {
	// This parameter represents the name of a Cloud-Account in Aviatrix controller.
	AccountName pulumi.StringInput
	// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
	//
	// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
	AttachedAviatrixTransitGateways pulumi.StringArrayInput
	// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
	AwsSideAsNumber pulumi.StringInput
	// TGW CIDRs.
	Cidrs pulumi.StringArrayInput
	// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
	CloudType pulumi.IntPtrInput
	// Enable Multicast.
	EnableMulticast pulumi.BoolPtrInput
	// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
	InspectionMode pulumi.StringPtrInput
	// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
	// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
	ManageSecurityDomain pulumi.BoolPtrInput
	// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
	// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
	ManageTransitGatewayAttachment pulumi.BoolPtrInput
	// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
	// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
	// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
	ManageVpcAttachment pulumi.BoolPtrInput
	// Region of cloud provider.
	Region pulumi.StringInput
	// Security Domains to create together with AWS TGW's creation.
	//
	// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
	SecurityDomains AviatrixAwsTgwSecurityDomainTypeArrayInput
	// Name of the AWS TGW which is going to be created.
	TgwName pulumi.StringInput
}

func (AviatrixAwsTgwArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aviatrixAwsTgwArgs)(nil)).Elem()
}

type AviatrixAwsTgwInput interface {
	pulumi.Input

	ToAviatrixAwsTgwOutput() AviatrixAwsTgwOutput
	ToAviatrixAwsTgwOutputWithContext(ctx context.Context) AviatrixAwsTgwOutput
}

func (*AviatrixAwsTgw) ElementType() reflect.Type {
	return reflect.TypeOf((**AviatrixAwsTgw)(nil)).Elem()
}

func (i *AviatrixAwsTgw) ToAviatrixAwsTgwOutput() AviatrixAwsTgwOutput {
	return i.ToAviatrixAwsTgwOutputWithContext(context.Background())
}

func (i *AviatrixAwsTgw) ToAviatrixAwsTgwOutputWithContext(ctx context.Context) AviatrixAwsTgwOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AviatrixAwsTgwOutput)
}

// AviatrixAwsTgwArrayInput is an input type that accepts AviatrixAwsTgwArray and AviatrixAwsTgwArrayOutput values.
// You can construct a concrete instance of `AviatrixAwsTgwArrayInput` via:
//
//	AviatrixAwsTgwArray{ AviatrixAwsTgwArgs{...} }
type AviatrixAwsTgwArrayInput interface {
	pulumi.Input

	ToAviatrixAwsTgwArrayOutput() AviatrixAwsTgwArrayOutput
	ToAviatrixAwsTgwArrayOutputWithContext(context.Context) AviatrixAwsTgwArrayOutput
}

type AviatrixAwsTgwArray []AviatrixAwsTgwInput

func (AviatrixAwsTgwArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AviatrixAwsTgw)(nil)).Elem()
}

func (i AviatrixAwsTgwArray) ToAviatrixAwsTgwArrayOutput() AviatrixAwsTgwArrayOutput {
	return i.ToAviatrixAwsTgwArrayOutputWithContext(context.Background())
}

func (i AviatrixAwsTgwArray) ToAviatrixAwsTgwArrayOutputWithContext(ctx context.Context) AviatrixAwsTgwArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AviatrixAwsTgwArrayOutput)
}

// AviatrixAwsTgwMapInput is an input type that accepts AviatrixAwsTgwMap and AviatrixAwsTgwMapOutput values.
// You can construct a concrete instance of `AviatrixAwsTgwMapInput` via:
//
//	AviatrixAwsTgwMap{ "key": AviatrixAwsTgwArgs{...} }
type AviatrixAwsTgwMapInput interface {
	pulumi.Input

	ToAviatrixAwsTgwMapOutput() AviatrixAwsTgwMapOutput
	ToAviatrixAwsTgwMapOutputWithContext(context.Context) AviatrixAwsTgwMapOutput
}

type AviatrixAwsTgwMap map[string]AviatrixAwsTgwInput

func (AviatrixAwsTgwMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AviatrixAwsTgw)(nil)).Elem()
}

func (i AviatrixAwsTgwMap) ToAviatrixAwsTgwMapOutput() AviatrixAwsTgwMapOutput {
	return i.ToAviatrixAwsTgwMapOutputWithContext(context.Background())
}

func (i AviatrixAwsTgwMap) ToAviatrixAwsTgwMapOutputWithContext(ctx context.Context) AviatrixAwsTgwMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AviatrixAwsTgwMapOutput)
}

type AviatrixAwsTgwOutput struct{ *pulumi.OutputState }

func (AviatrixAwsTgwOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AviatrixAwsTgw)(nil)).Elem()
}

func (o AviatrixAwsTgwOutput) ToAviatrixAwsTgwOutput() AviatrixAwsTgwOutput {
	return o
}

func (o AviatrixAwsTgwOutput) ToAviatrixAwsTgwOutputWithContext(ctx context.Context) AviatrixAwsTgwOutput {
	return o
}

// This parameter represents the name of a Cloud-Account in Aviatrix controller.
func (o AviatrixAwsTgwOutput) AccountName() pulumi.StringOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringOutput { return v.AccountName }).(pulumi.StringOutput)
}

// A list of Names of Aviatrix Transit Gateway to attach to one of the three default domains.
//
// Deprecated: Please set `manage_transit_gateway_attachment` to false, and use the standalone aviatrix_aws_tgw_transit_gateway_attachment resource instead.
func (o AviatrixAwsTgwOutput) AttachedAviatrixTransitGateways() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringArrayOutput { return v.AttachedAviatrixTransitGateways }).(pulumi.StringArrayOutput)
}

// BGP Local ASN (Autonomous System Number), Integer between 1-4294967294.
func (o AviatrixAwsTgwOutput) AwsSideAsNumber() pulumi.StringOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringOutput { return v.AwsSideAsNumber }).(pulumi.StringOutput)
}

// TGW CIDRs.
func (o AviatrixAwsTgwOutput) Cidrs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringArrayOutput { return v.Cidrs }).(pulumi.StringArrayOutput)
}

// Type of cloud service provider, requires an integer value. Supported for AWS (1) and AWS GOV (256). Default value: 1.
func (o AviatrixAwsTgwOutput) CloudType() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.IntPtrOutput { return v.CloudType }).(pulumi.IntPtrOutput)
}

// Enable Multicast.
func (o AviatrixAwsTgwOutput) EnableMulticast() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.BoolPtrOutput { return v.EnableMulticast }).(pulumi.BoolPtrOutput)
}

// Inspection mode. Valid values: 'Domain-based' and 'Connection-based'.
func (o AviatrixAwsTgwOutput) InspectionMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringPtrOutput { return v.InspectionMode }).(pulumi.StringPtrOutput)
}

// This parameter is a switch used to determine whether or not to manage security domains to the TGW using the
// aviatrix_aws_tgw resource. If this is set to false, security domains must be managed using the
// aviatrix_aws_tgw_security_domain resource. Valid values: true, false. Default value: true.
func (o AviatrixAwsTgwOutput) ManageSecurityDomain() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.BoolPtrOutput { return v.ManageSecurityDomain }).(pulumi.BoolPtrOutput)
}

// This parameter is a switch used to determine whether or not to manage transit gateway attachments to the TGW using the
// aviatrix_aws_tgw resource. If this is set to false, attachment of transit gateways must be done using the
// aviatrix_aws_tgw_transit_gateway_attachment resource. Valid values: true, false. Default value: true.
func (o AviatrixAwsTgwOutput) ManageTransitGatewayAttachment() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.BoolPtrOutput { return v.ManageTransitGatewayAttachment }).(pulumi.BoolPtrOutput)
}

// This parameter is a switch used to determine whether or not to manage VPC attachments to the TGW using the
// aviatrix_aws_tgw resource. If this is set to false, attachment of VPCs must be done using the
// aviatrix_aws_tgw_vpc_attachment resource. Valid values: true, false. Default value: true.
func (o AviatrixAwsTgwOutput) ManageVpcAttachment() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.BoolPtrOutput { return v.ManageVpcAttachment }).(pulumi.BoolPtrOutput)
}

// Region of cloud provider.
func (o AviatrixAwsTgwOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Security Domains to create together with AWS TGW's creation.
//
// Deprecated: Please set `manage_security_domain` to false, and use the standalone aviatrix_aws_tgw_network_domain resource instead.
func (o AviatrixAwsTgwOutput) SecurityDomains() AviatrixAwsTgwSecurityDomainTypeArrayOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) AviatrixAwsTgwSecurityDomainTypeArrayOutput { return v.SecurityDomains }).(AviatrixAwsTgwSecurityDomainTypeArrayOutput)
}

// TGW ID.
func (o AviatrixAwsTgwOutput) TgwId() pulumi.StringOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringOutput { return v.TgwId }).(pulumi.StringOutput)
}

// Name of the AWS TGW which is going to be created.
func (o AviatrixAwsTgwOutput) TgwName() pulumi.StringOutput {
	return o.ApplyT(func(v *AviatrixAwsTgw) pulumi.StringOutput { return v.TgwName }).(pulumi.StringOutput)
}

type AviatrixAwsTgwArrayOutput struct{ *pulumi.OutputState }

func (AviatrixAwsTgwArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AviatrixAwsTgw)(nil)).Elem()
}

func (o AviatrixAwsTgwArrayOutput) ToAviatrixAwsTgwArrayOutput() AviatrixAwsTgwArrayOutput {
	return o
}

func (o AviatrixAwsTgwArrayOutput) ToAviatrixAwsTgwArrayOutputWithContext(ctx context.Context) AviatrixAwsTgwArrayOutput {
	return o
}

func (o AviatrixAwsTgwArrayOutput) Index(i pulumi.IntInput) AviatrixAwsTgwOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AviatrixAwsTgw {
		return vs[0].([]*AviatrixAwsTgw)[vs[1].(int)]
	}).(AviatrixAwsTgwOutput)
}

type AviatrixAwsTgwMapOutput struct{ *pulumi.OutputState }

func (AviatrixAwsTgwMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AviatrixAwsTgw)(nil)).Elem()
}

func (o AviatrixAwsTgwMapOutput) ToAviatrixAwsTgwMapOutput() AviatrixAwsTgwMapOutput {
	return o
}

func (o AviatrixAwsTgwMapOutput) ToAviatrixAwsTgwMapOutputWithContext(ctx context.Context) AviatrixAwsTgwMapOutput {
	return o
}

func (o AviatrixAwsTgwMapOutput) MapIndex(k pulumi.StringInput) AviatrixAwsTgwOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AviatrixAwsTgw {
		return vs[0].(map[string]*AviatrixAwsTgw)[vs[1].(string)]
	}).(AviatrixAwsTgwOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AviatrixAwsTgwInput)(nil)).Elem(), &AviatrixAwsTgw{})
	pulumi.RegisterInputType(reflect.TypeOf((*AviatrixAwsTgwArrayInput)(nil)).Elem(), AviatrixAwsTgwArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AviatrixAwsTgwMapInput)(nil)).Elem(), AviatrixAwsTgwMap{})
	pulumi.RegisterOutputType(AviatrixAwsTgwOutput{})
	pulumi.RegisterOutputType(AviatrixAwsTgwArrayOutput{})
	pulumi.RegisterOutputType(AviatrixAwsTgwMapOutput{})
}
