// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aviatrix

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAviatrixGateway(ctx *pulumi.Context, args *LookupAviatrixGatewayArgs, opts ...pulumi.InvokeOption) (*LookupAviatrixGatewayResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupAviatrixGatewayResult
	err := ctx.Invoke("aviatrix:index/getAviatrixGateway:getAviatrixGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAviatrixGateway.
type LookupAviatrixGatewayArgs struct {
	GwName string `pulumi:"gwName"`
}

// A collection of values returned by getAviatrixGateway.
type LookupAviatrixGatewayResult struct {
	AccountName                      string `pulumi:"accountName"`
	AdditionalCidrs                  string `pulumi:"additionalCidrs"`
	AdditionalCidrsDesignatedGateway string `pulumi:"additionalCidrsDesignatedGateway"`
	AllocateNewEip                   bool   `pulumi:"allocateNewEip"`
	AvailabilityDomain               string `pulumi:"availabilityDomain"`
	AzureEipNameResourceGroup        string `pulumi:"azureEipNameResourceGroup"`
	CloudInstanceId                  string `pulumi:"cloudInstanceId"`
	CloudType                        int    `pulumi:"cloudType"`
	DuoApiHostname                   string `pulumi:"duoApiHostname"`
	DuoIntegrationKey                string `pulumi:"duoIntegrationKey"`
	DuoPushMode                      string `pulumi:"duoPushMode"`
	ElbDnsName                       string `pulumi:"elbDnsName"`
	ElbName                          string `pulumi:"elbName"`
	EnableDesignatedGateway          bool   `pulumi:"enableDesignatedGateway"`
	EnableElb                        bool   `pulumi:"enableElb"`
	EnableEncryptVolume              bool   `pulumi:"enableEncryptVolume"`
	EnableJumboFrame                 bool   `pulumi:"enableJumboFrame"`
	EnableLdap                       bool   `pulumi:"enableLdap"`
	EnableMonitorGatewaySubnets      bool   `pulumi:"enableMonitorGatewaySubnets"`
	EnablePublicSubnetFiltering      bool   `pulumi:"enablePublicSubnetFiltering"`
	EnableSpotInstance               bool   `pulumi:"enableSpotInstance"`
	EnableVpcDnsServer               bool   `pulumi:"enableVpcDnsServer"`
	EnableVpnNat                     bool   `pulumi:"enableVpnNat"`
	FaultDomain                      string `pulumi:"faultDomain"`
	FqdnLanCidr                      string `pulumi:"fqdnLanCidr"`
	FqdnLanInterface                 string `pulumi:"fqdnLanInterface"`
	FqdnLanVpcId                     string `pulumi:"fqdnLanVpcId"`
	GwName                           string `pulumi:"gwName"`
	GwSize                           string `pulumi:"gwSize"`
	// The provider-assigned unique ID for this managed resource.
	Id                                     string            `pulumi:"id"`
	IdleTimeout                            int               `pulumi:"idleTimeout"`
	ImageVersion                           string            `pulumi:"imageVersion"`
	InsaneMode                             bool              `pulumi:"insaneMode"`
	InsaneModeAz                           string            `pulumi:"insaneModeAz"`
	LdapBaseDn                             string            `pulumi:"ldapBaseDn"`
	LdapBindDn                             string            `pulumi:"ldapBindDn"`
	LdapServer                             string            `pulumi:"ldapServer"`
	LdapUsernameAttribute                  string            `pulumi:"ldapUsernameAttribute"`
	MaxVpnConn                             string            `pulumi:"maxVpnConn"`
	MonitorExcludeLists                    []string          `pulumi:"monitorExcludeLists"`
	NameServers                            string            `pulumi:"nameServers"`
	OktaUrl                                string            `pulumi:"oktaUrl"`
	OktaUsernameSuffix                     string            `pulumi:"oktaUsernameSuffix"`
	OtpMode                                string            `pulumi:"otpMode"`
	PeeringHaAvailabilityDomain            string            `pulumi:"peeringHaAvailabilityDomain"`
	PeeringHaAzureEipNameResourceGroup     string            `pulumi:"peeringHaAzureEipNameResourceGroup"`
	PeeringHaCloudInstanceId               string            `pulumi:"peeringHaCloudInstanceId"`
	PeeringHaFaultDomain                   string            `pulumi:"peeringHaFaultDomain"`
	PeeringHaGwName                        string            `pulumi:"peeringHaGwName"`
	PeeringHaGwSize                        string            `pulumi:"peeringHaGwSize"`
	PeeringHaImageVersion                  string            `pulumi:"peeringHaImageVersion"`
	PeeringHaInsaneModeAz                  string            `pulumi:"peeringHaInsaneModeAz"`
	PeeringHaPrivateIp                     string            `pulumi:"peeringHaPrivateIp"`
	PeeringHaPublicIp                      string            `pulumi:"peeringHaPublicIp"`
	PeeringHaSecurityGroupId               string            `pulumi:"peeringHaSecurityGroupId"`
	PeeringHaSoftwareVersion               string            `pulumi:"peeringHaSoftwareVersion"`
	PeeringHaSubnet                        string            `pulumi:"peeringHaSubnet"`
	PeeringHaZone                          string            `pulumi:"peeringHaZone"`
	PrivateIp                              string            `pulumi:"privateIp"`
	PublicDnsServer                        string            `pulumi:"publicDnsServer"`
	PublicIp                               string            `pulumi:"publicIp"`
	PublicSubnetFilteringGuardDutyEnforced bool              `pulumi:"publicSubnetFilteringGuardDutyEnforced"`
	PublicSubnetFilteringHaRouteTables     []string          `pulumi:"publicSubnetFilteringHaRouteTables"`
	PublicSubnetFilteringRouteTables       []string          `pulumi:"publicSubnetFilteringRouteTables"`
	RenegotiationInterval                  int               `pulumi:"renegotiationInterval"`
	SamlEnabled                            bool              `pulumi:"samlEnabled"`
	SearchDomains                          string            `pulumi:"searchDomains"`
	SecurityGroupId                        string            `pulumi:"securityGroupId"`
	SingleAzHa                             bool              `pulumi:"singleAzHa"`
	SingleIpSnat                           bool              `pulumi:"singleIpSnat"`
	SoftwareVersion                        string            `pulumi:"softwareVersion"`
	SplitTunnel                            bool              `pulumi:"splitTunnel"`
	SpotPrice                              string            `pulumi:"spotPrice"`
	Subnet                                 string            `pulumi:"subnet"`
	TagLists                               []string          `pulumi:"tagLists"`
	Tags                                   map[string]string `pulumi:"tags"`
	TunnelDetectionTime                    int               `pulumi:"tunnelDetectionTime"`
	VpcId                                  string            `pulumi:"vpcId"`
	VpcReg                                 string            `pulumi:"vpcReg"`
	VpnAccess                              bool              `pulumi:"vpnAccess"`
	VpnCidr                                string            `pulumi:"vpnCidr"`
	VpnProtocol                            string            `pulumi:"vpnProtocol"`
	Zone                                   string            `pulumi:"zone"`
}

func LookupAviatrixGatewayOutput(ctx *pulumi.Context, args LookupAviatrixGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupAviatrixGatewayResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAviatrixGatewayResult, error) {
			args := v.(LookupAviatrixGatewayArgs)
			r, err := LookupAviatrixGateway(ctx, &args, opts...)
			var s LookupAviatrixGatewayResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupAviatrixGatewayResultOutput)
}

// A collection of arguments for invoking getAviatrixGateway.
type LookupAviatrixGatewayOutputArgs struct {
	GwName pulumi.StringInput `pulumi:"gwName"`
}

func (LookupAviatrixGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAviatrixGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getAviatrixGateway.
type LookupAviatrixGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupAviatrixGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAviatrixGatewayResult)(nil)).Elem()
}

func (o LookupAviatrixGatewayResultOutput) ToLookupAviatrixGatewayResultOutput() LookupAviatrixGatewayResultOutput {
	return o
}

func (o LookupAviatrixGatewayResultOutput) ToLookupAviatrixGatewayResultOutputWithContext(ctx context.Context) LookupAviatrixGatewayResultOutput {
	return o
}

func (o LookupAviatrixGatewayResultOutput) AccountName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.AccountName }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) AdditionalCidrs() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.AdditionalCidrs }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) AdditionalCidrsDesignatedGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.AdditionalCidrsDesignatedGateway }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) AllocateNewEip() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.AllocateNewEip }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) AvailabilityDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.AvailabilityDomain }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) AzureEipNameResourceGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.AzureEipNameResourceGroup }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) CloudInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.CloudInstanceId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) CloudType() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) int { return v.CloudType }).(pulumi.IntOutput)
}

func (o LookupAviatrixGatewayResultOutput) DuoApiHostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.DuoApiHostname }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) DuoIntegrationKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.DuoIntegrationKey }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) DuoPushMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.DuoPushMode }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) ElbDnsName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.ElbDnsName }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) ElbName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.ElbName }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableDesignatedGateway() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableDesignatedGateway }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableElb() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableElb }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableEncryptVolume() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableEncryptVolume }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableJumboFrame() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableJumboFrame }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableLdap() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableLdap }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableMonitorGatewaySubnets() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableMonitorGatewaySubnets }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnablePublicSubnetFiltering() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnablePublicSubnetFiltering }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableSpotInstance() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableSpotInstance }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableVpcDnsServer() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableVpcDnsServer }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) EnableVpnNat() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.EnableVpnNat }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) FaultDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.FaultDomain }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) FqdnLanCidr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.FqdnLanCidr }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) FqdnLanInterface() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.FqdnLanInterface }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) FqdnLanVpcId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.FqdnLanVpcId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) GwName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.GwName }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) GwSize() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.GwSize }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAviatrixGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) IdleTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) int { return v.IdleTimeout }).(pulumi.IntOutput)
}

func (o LookupAviatrixGatewayResultOutput) ImageVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.ImageVersion }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) InsaneMode() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.InsaneMode }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) InsaneModeAz() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.InsaneModeAz }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) LdapBaseDn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.LdapBaseDn }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) LdapBindDn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.LdapBindDn }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) LdapServer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.LdapServer }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) LdapUsernameAttribute() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.LdapUsernameAttribute }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) MaxVpnConn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.MaxVpnConn }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) MonitorExcludeLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) []string { return v.MonitorExcludeLists }).(pulumi.StringArrayOutput)
}

func (o LookupAviatrixGatewayResultOutput) NameServers() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.NameServers }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) OktaUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.OktaUrl }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) OktaUsernameSuffix() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.OktaUsernameSuffix }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) OtpMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.OtpMode }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaAvailabilityDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaAvailabilityDomain }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaAzureEipNameResourceGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaAzureEipNameResourceGroup }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaCloudInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaCloudInstanceId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaFaultDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaFaultDomain }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaGwName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaGwName }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaGwSize() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaGwSize }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaImageVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaImageVersion }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaInsaneModeAz() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaInsaneModeAz }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaPrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaPrivateIp }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaPublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaPublicIp }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaSecurityGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaSecurityGroupId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaSoftwareVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaSoftwareVersion }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaSubnet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaSubnet }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PeeringHaZone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PeeringHaZone }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PublicDnsServer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PublicDnsServer }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) PublicSubnetFilteringGuardDutyEnforced() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.PublicSubnetFilteringGuardDutyEnforced }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) PublicSubnetFilteringHaRouteTables() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) []string { return v.PublicSubnetFilteringHaRouteTables }).(pulumi.StringArrayOutput)
}

func (o LookupAviatrixGatewayResultOutput) PublicSubnetFilteringRouteTables() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) []string { return v.PublicSubnetFilteringRouteTables }).(pulumi.StringArrayOutput)
}

func (o LookupAviatrixGatewayResultOutput) RenegotiationInterval() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) int { return v.RenegotiationInterval }).(pulumi.IntOutput)
}

func (o LookupAviatrixGatewayResultOutput) SamlEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.SamlEnabled }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) SearchDomains() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.SearchDomains }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) SecurityGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.SecurityGroupId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) SingleAzHa() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.SingleAzHa }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) SingleIpSnat() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.SingleIpSnat }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) SoftwareVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.SoftwareVersion }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) SplitTunnel() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.SplitTunnel }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) SpotPrice() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.SpotPrice }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) Subnet() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.Subnet }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) TagLists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) []string { return v.TagLists }).(pulumi.StringArrayOutput)
}

func (o LookupAviatrixGatewayResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func (o LookupAviatrixGatewayResultOutput) TunnelDetectionTime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) int { return v.TunnelDetectionTime }).(pulumi.IntOutput)
}

func (o LookupAviatrixGatewayResultOutput) VpcId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.VpcId }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) VpcReg() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.VpcReg }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) VpnAccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) bool { return v.VpnAccess }).(pulumi.BoolOutput)
}

func (o LookupAviatrixGatewayResultOutput) VpnCidr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.VpnCidr }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) VpnProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.VpnProtocol }).(pulumi.StringOutput)
}

func (o LookupAviatrixGatewayResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAviatrixGatewayResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAviatrixGatewayResultOutput{})
}
