// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix.Inputs
{

    public sealed class AviatrixAwsTgwVpnConnVpnTunnelDataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("lastStatusChangeTime")]
        public Input<string>? LastStatusChangeTime { get; set; }

        [Input("routeCount")]
        public Input<int>? RouteCount { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("statusMessage")]
        public Input<string>? StatusMessage { get; set; }

        [Input("tgwAsn")]
        public Input<string>? TgwAsn { get; set; }

        [Input("tunnelName")]
        public Input<string>? TunnelName { get; set; }

        [Input("vpnInsideAddress")]
        public Input<string>? VpnInsideAddress { get; set; }

        [Input("vpnOutsideAddress")]
        public Input<string>? VpnOutsideAddress { get; set; }

        public AviatrixAwsTgwVpnConnVpnTunnelDataGetArgs()
        {
        }
        public static new AviatrixAwsTgwVpnConnVpnTunnelDataGetArgs Empty => new AviatrixAwsTgwVpnConnVpnTunnelDataGetArgs();
    }
}
