// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aviatrix.Inputs
{

    public sealed class AviatrixAwsTgwSecurityDomainArgs : global::Pulumi.ResourceArgs
    {
        [Input("attachedVpcs")]
        private InputList<Inputs.AviatrixAwsTgwSecurityDomainAttachedVpcArgs>? _attachedVpcs;
        [Obsolete(@"Please set `manage_vpc_attachment` to false, and use the standalone aviatrix_aws_tgw_vpc_attachment resource instead.")]
        public InputList<Inputs.AviatrixAwsTgwSecurityDomainAttachedVpcArgs> AttachedVpcs
        {
            get => _attachedVpcs ?? (_attachedVpcs = new InputList<Inputs.AviatrixAwsTgwSecurityDomainAttachedVpcArgs>());
            set => _attachedVpcs = value;
        }

        [Input("aviatrixFirewall")]
        public Input<bool>? AviatrixFirewall { get; set; }

        [Input("connectedDomains")]
        private InputList<string>? _connectedDomains;
        public InputList<string> ConnectedDomains
        {
            get => _connectedDomains ?? (_connectedDomains = new InputList<string>());
            set => _connectedDomains = value;
        }

        [Input("nativeEgress")]
        public Input<bool>? NativeEgress { get; set; }

        [Input("nativeFirewall")]
        public Input<bool>? NativeFirewall { get; set; }

        [Input("securityDomainName", required: true)]
        public Input<string> SecurityDomainName { get; set; } = null!;

        public AviatrixAwsTgwSecurityDomainArgs()
        {
        }
        public static new AviatrixAwsTgwSecurityDomainArgs Empty => new AviatrixAwsTgwSecurityDomainArgs();
    }
}
