// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class AviatrixFirewall extends pulumi.CustomResource {
    /**
     * Get an existing AviatrixFirewall resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AviatrixFirewallState, opts?: pulumi.CustomResourceOptions): AviatrixFirewall {
        return new AviatrixFirewall(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'aviatrix:index/aviatrixFirewall:AviatrixFirewall';

    /**
     * Returns true if the given object is an instance of AviatrixFirewall.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AviatrixFirewall {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AviatrixFirewall.__pulumiType;
    }

    /**
     * Indicates whether enable logging or not. Valid values: true, false. Default value: false.
     */
    public readonly baseLogEnabled!: pulumi.Output<boolean | undefined>;
    /**
     * New base policy.
     */
    public readonly basePolicy!: pulumi.Output<string | undefined>;
    /**
     * The name of gateway.
     */
    public readonly gwName!: pulumi.Output<string>;
    /**
     * Enable to manage firewall policies via in-line rules. If false, policies must be managed using
     * `aviatrix_firewall_policy` resources.
     */
    public readonly manageFirewallPolicies!: pulumi.Output<boolean | undefined>;
    /**
     * New access policy for the gateway.
     */
    public readonly policies!: pulumi.Output<outputs.AviatrixFirewallPolicy[] | undefined>;

    /**
     * Create a AviatrixFirewall resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AviatrixFirewallArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AviatrixFirewallArgs | AviatrixFirewallState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AviatrixFirewallState | undefined;
            resourceInputs["baseLogEnabled"] = state ? state.baseLogEnabled : undefined;
            resourceInputs["basePolicy"] = state ? state.basePolicy : undefined;
            resourceInputs["gwName"] = state ? state.gwName : undefined;
            resourceInputs["manageFirewallPolicies"] = state ? state.manageFirewallPolicies : undefined;
            resourceInputs["policies"] = state ? state.policies : undefined;
        } else {
            const args = argsOrState as AviatrixFirewallArgs | undefined;
            if ((!args || args.gwName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'gwName'");
            }
            resourceInputs["baseLogEnabled"] = args ? args.baseLogEnabled : undefined;
            resourceInputs["basePolicy"] = args ? args.basePolicy : undefined;
            resourceInputs["gwName"] = args ? args.gwName : undefined;
            resourceInputs["manageFirewallPolicies"] = args ? args.manageFirewallPolicies : undefined;
            resourceInputs["policies"] = args ? args.policies : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AviatrixFirewall.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AviatrixFirewall resources.
 */
export interface AviatrixFirewallState {
    /**
     * Indicates whether enable logging or not. Valid values: true, false. Default value: false.
     */
    baseLogEnabled?: pulumi.Input<boolean>;
    /**
     * New base policy.
     */
    basePolicy?: pulumi.Input<string>;
    /**
     * The name of gateway.
     */
    gwName?: pulumi.Input<string>;
    /**
     * Enable to manage firewall policies via in-line rules. If false, policies must be managed using
     * `aviatrix_firewall_policy` resources.
     */
    manageFirewallPolicies?: pulumi.Input<boolean>;
    /**
     * New access policy for the gateway.
     */
    policies?: pulumi.Input<pulumi.Input<inputs.AviatrixFirewallPolicy>[]>;
}

/**
 * The set of arguments for constructing a AviatrixFirewall resource.
 */
export interface AviatrixFirewallArgs {
    /**
     * Indicates whether enable logging or not. Valid values: true, false. Default value: false.
     */
    baseLogEnabled?: pulumi.Input<boolean>;
    /**
     * New base policy.
     */
    basePolicy?: pulumi.Input<string>;
    /**
     * The name of gateway.
     */
    gwName: pulumi.Input<string>;
    /**
     * Enable to manage firewall policies via in-line rules. If false, policies must be managed using
     * `aviatrix_firewall_policy` resources.
     */
    manageFirewallPolicies?: pulumi.Input<boolean>;
    /**
     * New access policy for the gateway.
     */
    policies?: pulumi.Input<pulumi.Input<inputs.AviatrixFirewallPolicy>[]>;
}
