// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class AviatrixVpnProfile extends pulumi.CustomResource {
    /**
     * Get an existing AviatrixVpnProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AviatrixVpnProfileState, opts?: pulumi.CustomResourceOptions): AviatrixVpnProfile {
        return new AviatrixVpnProfile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'aviatrix:index/aviatrixVpnProfile:AviatrixVpnProfile';

    /**
     * Returns true if the given object is an instance of AviatrixVpnProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AviatrixVpnProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AviatrixVpnProfile.__pulumiType;
    }

    /**
     * Base policy rule of the profile to be added. Enter 'allow_all' or 'deny_all'.
     */
    public readonly baseRule!: pulumi.Output<string | undefined>;
    public readonly manageUserAttachment!: pulumi.Output<boolean | undefined>;
    /**
     * name for the VPN profile.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * New security policy for the profile.
     */
    public readonly policies!: pulumi.Output<outputs.AviatrixVpnProfilePolicy[] | undefined>;
    /**
     * List of VPN users to attach to this profile.
     */
    public readonly users!: pulumi.Output<string[] | undefined>;

    /**
     * Create a AviatrixVpnProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AviatrixVpnProfileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AviatrixVpnProfileArgs | AviatrixVpnProfileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AviatrixVpnProfileState | undefined;
            resourceInputs["baseRule"] = state ? state.baseRule : undefined;
            resourceInputs["manageUserAttachment"] = state ? state.manageUserAttachment : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["policies"] = state ? state.policies : undefined;
            resourceInputs["users"] = state ? state.users : undefined;
        } else {
            const args = argsOrState as AviatrixVpnProfileArgs | undefined;
            resourceInputs["baseRule"] = args ? args.baseRule : undefined;
            resourceInputs["manageUserAttachment"] = args ? args.manageUserAttachment : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["policies"] = args ? args.policies : undefined;
            resourceInputs["users"] = args ? args.users : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AviatrixVpnProfile.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AviatrixVpnProfile resources.
 */
export interface AviatrixVpnProfileState {
    /**
     * Base policy rule of the profile to be added. Enter 'allow_all' or 'deny_all'.
     */
    baseRule?: pulumi.Input<string>;
    manageUserAttachment?: pulumi.Input<boolean>;
    /**
     * name for the VPN profile.
     */
    name?: pulumi.Input<string>;
    /**
     * New security policy for the profile.
     */
    policies?: pulumi.Input<pulumi.Input<inputs.AviatrixVpnProfilePolicy>[]>;
    /**
     * List of VPN users to attach to this profile.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a AviatrixVpnProfile resource.
 */
export interface AviatrixVpnProfileArgs {
    /**
     * Base policy rule of the profile to be added. Enter 'allow_all' or 'deny_all'.
     */
    baseRule?: pulumi.Input<string>;
    manageUserAttachment?: pulumi.Input<boolean>;
    /**
     * name for the VPN profile.
     */
    name?: pulumi.Input<string>;
    /**
     * New security policy for the profile.
     */
    policies?: pulumi.Input<pulumi.Input<inputs.AviatrixVpnProfilePolicy>[]>;
    /**
     * List of VPN users to attach to this profile.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
}
